### ISSUE TITLE
Sketch in Windows

### ISSUE THREAD

**Issue by sajaddp** [muicss/mui-design-files#2]
Hello,
Which program can open "mui-cssjs.sketch" in Windows OS?

**Comment by amorey** [comment]
"Sketch" is a design program for OS X. It might be possible to export the files to SVG. Would that help?

**Comment by sajaddp** [comment]
It's good idea!
I can use SVG files in Illustrator

**Comment by amorey** [comment]
Ok, great. I can look into it tonight.

**Comment by amorey** [comment]
svg files are in the 'svg' directory in master:
https://github.com/muicss/mui-design-files

Let me know if it works for you!

**Comment by sajaddp** [comment]
Very thanks :)
all files worked but windows LTR users need to install this font: "Helvetica Neue";

EDIT:
- in RTL users need to change fonts.
- I'm RTL member.
