### ISSUE TITLE
navbar support

### ISSUE THREAD

**Issue by ARKKYN** [muicss/mui-design-files#3]
sir please add a responsive navbar support like in bootstrap

**Comment by amorey** [comment]
Hi @devmakk! Can you be more specific with what you mean by responsive navbar support? The MUI "appbar" uses the Material Design appbar specs.

Are you making a request regarding the Sketch files or the CSS framework itself? This is the repository for the Sketch files and the repository for the CSS framework is here:
https://github.com/muicss/mui

**Comment by ARKKYN** [comment]
I mean when I view it in mobile device the navigation bar is not responsive

**Comment by amorey** [comment]
Ok, can you file a bug report in the MUI project including a description of how to reproduce it?
https://github.com/muicss/mui/issues

What do you mean by the nav bar is not responsive? The `.mui-appbar` element is just a solid block with dimensions that are set based on the browser width and device orientation.
